### ISSUE TITLE
[Error: NeoAgent 'Backend' has no configured database]and [Generated cypher with extra characters]

### ISSUE THREAD

**Issue by keyilizzie** [neo4j-labs/neoconverse#5]
![1721098156642](https://github.com/user-attachments/assets/c44522a1-8985-4297-84e2-b6134f6b0cc6)
(llama_factory) (base) [liukeyi@ibgpu09 neoconverse]$ npm run start

> start
> next start

  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 513ms
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Error: NeoAgent 'Backend' has no configured database
    at run (/home/liukeyi/neoconverse/.next/server/pages/api/neoapi.js:12:1665)
    at neoapi_initAgents (/home/liukeyi/neoconverse/.next/server/pages/api/neoapi.js:12:1221)
    at Object.8879 (/home/liukeyi/neoconverse/.next/server/pages/api/neoapi.js:12:2070)
    at __webpack_require__ (/home/liukeyi/neoconverse/.next/server/edge-runtime-webpack.js:25:42)
    at /home/liukeyi/neoconverse/.next/server/pages/api/neoapi.js:50:186701
    at webpackJsonpCallback (/home/liukeyi/neoconverse/.next/server/edge-runtime-webpack.js:158:39)
    at /home/liukeyi/neoconverse/.next/server/pages/api/neoapi.js:1:51
    at Script.runInContext (node:vm:141:12)
    at runInContext (node:vm:297:6)
    at evaluateInContext (/home/liukeyi/neoconverse/node_modules/next/dist/server/web/sandbox/context.js:357:38)
err:  [Error: NeoAgent 'Backend' has no configured database]

**Comment by kumarss20** [comment]
Hey @keyilizzie, thank you for trying out NeoConverse. Have you pulled the latest code and tried building it? Let me know if the latest pull doesn't work.

**Comment by shawndubeMSFT** [comment]
See: https://sdk.vercel.ai/docs/troubleshooting/common-issues/strange-stream-output
